### ISSUE TITLE
Randomness?!

### ISSUE THREAD

**Issue by zeroknots** [simontianx/OnChainDiscreteRNG#3]
To me the numbers look very far from random. Am I using it wrong? 

seed: 43294655272905728554912579510480359650391174114007650256555046040515421218551

`
750,1625,-750,-1125,625,750,0,-750,-625,-750,-1000,-250,-750,875,-1125,-1625,1000,500,375,875,625,0,125,-750,-1125,-500,1625,750,1250,1125,-1375,750,500,-250,1125,-625,625,0,-250,-875,375,750,1500,-500,375,1250,125,-750,125,500,1375,1375,-2000,250,-1625,750,-1125,-375,-125,-1000,1000,-2125,375,375,-125,-1750,375,-125,-625,1375,0,-1250,-500,-875,-500,1500,-875,-750,-1375,-750,250,-1000,375,-875,625,500,-625,-1375,1125,250,-125,-250,500,1125,-750,2000,500,-875,375,-250
`

**Comment by simontianx** [comment]
@zeroknots Hi thanks for the question and it is a totally legitmate one. The randomness of the sequence of numbers provided can be understood as a discrete approximation to the Gaussian distribution. A more ideal version using the Binomial approximation to normal distribution can be found [here](https://en.wikipedia.org/wiki/Binomial_distribution). The algorithm proposed in this article is a more generalized case when the probababilities of digits being 1 are not all identical, but the spirit is the same, to approximate the continuous Gaussian distribution with discrete numbers.

**Comment by simontianx** [comment]
More specifically, this sequence is random with mean 0 and standard deviation 1000 which is a good approximation to `N(0, 1000^2)` with precision up to three decimal points. See the empirical CDF of the sample given below.

![image](https://user-images.githubusercontent.com/9939278/196609328-f57ed70a-5c8d-4586-ad51-aa7e01e32288.png)
